"""empty message

Revision ID: 00ee9b64fde8
Revises: 0d06de8b3af0
Create Date: 2025-02-27 18:52:34.343599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ee9b64fde8'
down_revision = '0d06de8b3af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.drop_index('email')
        batch_op.drop_index('name')
        batch_op.drop_index('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
