"""empty message

Revision ID: 2ad268154e86
Revises: a9f304b5121c
Create Date: 2025-03-06 11:49:10.957630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ad268154e86'
down_revision = 'a9f304b5121c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
        batch_op.drop_column('prifile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prifile_picture', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
